/**
 * Parity tests: netlify/functions/lib/bandSetlistMergeRule.js must agree
 * with lib/bandSetlistMerge.js on every case, always.
 *
 * WHY THIS FILE EXISTS. Same reason as festivalMatchParity.test.js. The
 * merge rule has to exist twice — once as the app's ESM module for the
 * client-side add and re-scan paths, once as CommonJS the admin backfill
 * can require without a build step to resolve `@/lib`. Two definitions of
 * one rule is a standing invitation to drift.
 *
 * Drift here is unusually expensive. The rule's whole job is not destroying
 * a user's ratings and hand-added songs, and the two copies run over the
 * same documents: the client copy when a show is added, the server copy
 * when admin-resync-setlists.js backfills it. A server copy that had
 * quietly lost the keep-manual-songs branch would delete data the client
 * copy preserves, and the dry-run report — which is generated by the server
 * copy — would show the deletion as expected behaviour.
 *
 * The CJS copy also carries its own port of normalizeSongTitle from
 * lib/utils.js, since it cannot import it. That port is compared against
 * the real one directly, because every match in the rule keys off it.
 *
 * Run with:
 *   node --experimental-loader ./lib/__tests__/alias-loader.mjs lib/__tests__/bandSetlistMergeParity.test.js
 */

import assert from 'assert';
import { createRequire } from 'module';
import * as esm from '@/lib/bandSetlistMerge';
import { normalizeSongTitle } from '@/lib/utils';

const require = createRequire(import.meta.url);
const cjs = require('../../netlify/functions/lib/bandSetlistMergeRule.js');

let passed = 0;
let failed = 0;

function test(name, fn) {
  try {
    fn();
    passed++;
  } catch (err) {
    failed++;
    console.error(`✗ ${name}\n  ${err.message}`);
  }
}

function stored(name, set, extra = {}) {
  return { id: `old-${name}`, name, set, cover: null, tape: false, ...extra };
}
function incoming(name, set, extra = {}) {
  return { id: `new-${name}`, name, set, cover: null, tape: false, ...extra };
}

// Runs one case through both implementations and asserts they agree on the
// resulting setlist AND on the summary — the summary is what the dry run
// prints, so a divergence there is a divergence in what a human is told.
function assertAgree(label, existing, incomingSongs) {
  const a = esm.mergeBandSetlist(existing, incomingSongs);
  const b = cjs.mergeBandSetlist(existing, incomingSongs);

  assert.strictEqual(a.changed, b.changed, `${label}: changed disagrees`);
  assert.deepStrictEqual(a.setlist, b.setlist, `${label}: setlist disagrees`);
  assert.deepStrictEqual(a.summary, b.summary, `${label}: summary disagrees`);
  assert.strictEqual(
    esm.describeSummary(a.summary),
    cjs.describeSummary(b.summary),
    `${label}: describeSummary disagrees`
  );
}

// ── The normalizer the whole rule keys off ────────────────────────────

test('the CJS normalizeSongTitle port matches lib/utils.js exactly', () => {
  const cases = [
    "Mike's Song", 'Mikes Song', 'MIKES SONG', '  Tweezer  ',
    'Ashes//Dust', 'Ashes // Dust', 'Ashes / Dust',
    'Wilson (Live)', 'Wilson - Live', 'Tweezer (Remastered 2019)',
    'Down with Disease - Remaster', 'Also Sprach Zarathustra',
    'Rock and Roll, Hoochie Koo', '', null, undefined,
    'Song   With    Spaces', 'Éclair', '2001', 'A.C./D.C.',
    'Icculus!', 'Weekapaug Groove', 'You Enjoy Myself',
  ];
  cases.forEach((input) => {
    assert.strictEqual(
      cjs.normalizeSongTitle(input),
      normalizeSongTitle(input),
      `normalizeSongTitle(${JSON.stringify(input)}) disagrees`
    );
  });
});

test('the two copies declare the same user-owned and source field lists', () => {
  // If one copy learned about a new user-authored field and the other
  // didn't, the one that didn't would silently discard it.
  assert.deepStrictEqual(cjs.USER_OWNED_SONG_FIELDS, esm.USER_OWNED_SONG_FIELDS);
  assert.deepStrictEqual(cjs.SOURCE_SONG_FIELDS, esm.SOURCE_SONG_FIELDS);
});

// ── The rule itself, case for case ────────────────────────────────────

test('parity: empty incoming writes nothing', () => {
  assertAgree('empty incoming', [stored('Hot Tea', 'Set I')], []);
});

test('parity: null and undefined incoming', () => {
  assertAgree('null incoming', [stored('Hot Tea', 'Set I')], null);
  assertAgree('undefined incoming', [stored('Hot Tea', 'Set I')], undefined);
});

test('parity: both sides empty', () => {
  assertAgree('both empty', [], []);
});

test('parity: a first fetch onto a show with no setlist', () => {
  assertAgree('first fetch', [], [incoming('Hot Tea', 'Set I'), incoming('Arrow', 'Set I')]);
});

test('parity: ratings and comments carried over', () => {
  assertAgree(
    'user fields',
    [stored('Hot Tea', 'Set I', { rating: 9, comment: 'huge' }), stored('Arrow', 'Set I', { rating: 0 })],
    [incoming('Hot Tea', 'Set I'), incoming('Arrow', 'Set I')]
  );
});

test('parity: a hand-added song the source does not have', () => {
  assertAgree(
    'manual kept',
    [
      stored('Hot Tea', 'Set I'),
      stored('Tumble', 'Set II'),
      stored('Mine', 'Set II', { manuallyAdded: true, rating: 8 }),
      stored('My Encore', 'Encore II', { manuallyAdded: true }),
    ],
    [incoming('Hot Tea', 'Set I'), incoming('Tumble', 'Set II'), incoming('Time to Flee', 'Encore')]
  );
});

test('parity: a stale source song removed', () => {
  assertAgree(
    'removal',
    [stored('Hot Tea', 'Set I'), stored('Wrongly Listed', 'Set I')],
    [incoming('Hot Tea', 'Set I')]
  );
});

test('parity: moved within a set', () => {
  assertAgree(
    'moved position',
    [stored('A', 'Set I'), stored('B', 'Set I', { rating: 6 })],
    [incoming('B', 'Set I'), incoming('A', 'Set I')]
  );
});

test('parity: moved to another set', () => {
  assertAgree('moved set', [stored('Tumble', 'Set I', { rating: 4 })], [incoming('Tumble', 'Set II')]);
});

test('parity: title spellings that normalize to the same key', () => {
  assertAgree(
    'normalized match',
    [stored("Mike's Song", 'Set II', { rating: 10 })],
    [incoming('Mikes Song', 'Set II')]
  );
});

test('parity: the same song played twice in one show', () => {
  assertAgree(
    'repeat performance',
    [
      { ...stored('Tweezer', 'Set II'), id: 'old-tweezer-1', rating: 9 },
      { ...stored('Tweezer', 'Encore'), id: 'old-tweezer-2', rating: 7 },
    ],
    [incoming('Tweezer', 'Set II'), incoming('Tweezer', 'Encore')]
  );
});

test('parity: the full band-source field set arriving at once', () => {
  assertAgree(
    'all source fields',
    [stored('Hot Tea', 'Set I', { rating: 5, footnote: 'old note' })],
    [
      incoming('Hot Tea', 'Set I', {
        transitionMark: '->', tape: true, footnote: 'corrected', jamchart: true,
        jamchartNote: 'the big one', sourceGap: 0, songId: 'eg-hot-tea',
        songSlug: 'hot-tea', sourceOpener: true,
      }),
      incoming('Arrow', 'Set I', { transitionMark: '>', tape: true, sourceGap: 8 }),
    ]
  );
});

test('parity: blank titles on both sides', () => {
  assertAgree('blank titles', [stored('', 'Set I', { rating: 3 })], [incoming('', 'Set I')]);
});

test('parity: a song with no set label at all', () => {
  assertAgree(
    'missing set label',
    [{ id: 'x', name: 'Loose Song', rating: 2 }],
    [{ id: 'y', name: 'Loose Song' }]
  );
});

test('parity: a realistic full two-set show with an encore', () => {
  const existing = [
    stored('Hot Tea', 'Set I', { rating: 8 }),
    stored('Arrow', 'Set I'),
    stored('Madhuvan', 'Set I', { comment: 'first time' }),
    stored('Tumble', 'Set II', { rating: 10 }),
    stored('Dripfield', 'Set II'),
    stored('Bonus I Remember', 'Set II', { manuallyAdded: true, rating: 6 }),
    stored('Time to Flee', 'Encore'),
  ];
  const incomingSongs = [
    incoming('Hot Tea', 'Set I', { transitionMark: '>', tape: true, footnote: 'Tom Sawyer tease', sourceGap: 3 }),
    incoming('Madhuvan', 'Set I', { sourceGap: 0 }),
    incoming('Arrow', 'Set I', { jamchart: true, jamchartNote: 'patient build', sourceGap: 8 }),
    incoming('Tumble', 'Set II', { sourceGap: 12 }),
    incoming('Red Bird', 'Set II', { transitionMark: '->', tape: true }),
    incoming('Time to Flee', 'Encore', { footnote: 'Guest: Marcus King' }),
    incoming('Rockdale', 'Encore II'),
  ];
  assertAgree('full show', existing, incomingSongs);
});

// ── Summary ─────────────────────────────────────────
console.log(`\n${passed} passed, ${failed} failed\n`);
process.exit(failed > 0 ? 1 : 0);
